"""Schema and licence-policy checks for the Linux distribution SBOM artifacts.

The artifacts under test are committed evidence, regenerated by
``python tools/generate_sbom.py`` after ``scripts/build-linux.sh``:

- ``.agent_workspace/v1.1/linux-sbom.json`` (CycloneDX-shaped, bundle-scoped)
- ``packaging/SBOM.json`` (SPDX-shaped, build-venv-scoped)
- ``.agent_workspace/v1.1/linux-build-report.json`` (distribution gate report)

The policy assertions mirror THIRD_PARTY_LICENSES.md: the default profile
carries no plain-GPL component, and pedalboard never reaches a bundle.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CYCLONEDX_PATH = REPOSITORY_ROOT / ".agent_workspace" / "v1.1" / "linux-sbom.json"
SPDX_PATH = REPOSITORY_ROOT / "packaging" / "SBOM.json"
REPORT_PATH = REPOSITORY_ROOT / ".agent_workspace" / "v1.1" / "linux-build-report.json"

REGENERATE_HINT = (
    "run `scripts/build-linux.sh` then `python tools/generate_sbom.py` "
    "to publish the distribution SBOM artifacts"
)


def _load(path: Path) -> dict:
    assert path.is_file(), f"missing {path.relative_to(REPOSITORY_ROOT)}; {REGENERATE_HINT}"
    return json.loads(path.read_text(encoding="utf-8"))


def _properties(component: dict) -> dict[str, str]:
    return {p["name"]: p["value"] for p in component.get("properties", [])}


def _is_plain_gpl(expression: str) -> bool:
    """True when every alternative of the expression is unexceptioned GPL."""
    return all(
        bool(re.search(r"(?<!L)GPL", alt)) and "exception" not in alt.lower()
        for alt in expression.split(" OR ")
    )


# -- CycloneDX bundle BOM -------------------------------------------------------


def test_cyclonedx_document_shape() -> None:
    sbom = _load(CYCLONEDX_PATH)

    assert sbom["bomFormat"] == "CycloneDX"
    assert sbom["specVersion"] == "1.5"
    assert sbom["serialNumber"].startswith("urn:uuid:")
    assert sbom["version"] == 1

    metadata = sbom["metadata"]
    assert metadata["timestamp"]
    assert metadata["tools"][0]["name"] == "tools/generate_sbom.py"

    root = metadata["component"]
    assert root["type"] == "application"
    assert root["name"] == "audio-studio"
    assert root["version"]
    assert root["licenses"][0]["license"]["id"] == "MIT"


def test_cyclonedx_components_have_versions_and_licenses() -> None:
    sbom = _load(CYCLONEDX_PATH)
    components = sbom["components"]
    assert len(components) > 0

    for component in components:
        assert component["name"], component
        assert component["version"], component
        licenses = component["licenses"]
        assert licenses, f"{component['name']} has no licence entry"
        assert licenses[0]["license"]["id"], f"{component['name']} has an empty licence"

        properties = _properties(component)
        assert "audio-studio:profile" in properties, component["name"]
        assert properties["audio-studio:bundled"] in {"true", "false"}, component["name"]

        if component.get("purl"):
            assert component["purl"].startswith("pkg:pypi/"), component["name"]


def test_cyclonedx_bundled_components_carry_evidence() -> None:
    sbom = _load(CYCLONEDX_PATH)
    bundled = [c for c in sbom["components"] if _properties(c)["audio-studio:bundled"] == "true"]
    assert bundled, "an SBOM of a built bundle must mark some components as bundled"
    for component in bundled:
        evidence = _properties(component)["audio-studio:bundle-evidence"]
        assert evidence and evidence != "absent", component["name"]


def test_no_pedalboard_in_default_profile_or_bundle() -> None:
    sbom = _load(CYCLONEDX_PATH)
    for component in sbom["components"]:
        properties = _properties(component)
        if component["name"].lower() == "pedalboard":
            assert properties["audio-studio:profile"] != "default"
            assert properties["audio-studio:bundled"] == "false", (
                "pedalboard (GPL-3.0) inside the bundle relicenses the whole "
                "distribution; see THIRD_PARTY_LICENSES.md"
            )
        if properties["audio-studio:profile"] == "default":
            assert component["name"].lower() != "pedalboard"


def test_default_profile_has_no_plain_gpl_license() -> None:
    sbom = _load(CYCLONEDX_PATH)
    for component in sbom["components"]:
        if _properties(component)["audio-studio:profile"] != "default":
            continue
        license_id = component["licenses"][0]["license"]["id"]
        assert not _is_plain_gpl(license_id), (
            f"{component['name']} resolves to a plain-GPL licence ({license_id}) "
            "inside the default profile"
        )


# -- SPDX venv document ----------------------------------------------------------


def test_spdx_document_shape() -> None:
    spdx = _load(SPDX_PATH)

    assert spdx["spdxVersion"] == "SPDX-2.3"
    assert spdx["dataLicense"] == "CC0-1.0"
    assert spdx["SPDXID"] == "SPDXRef-DOCUMENT"
    assert spdx["name"]
    assert spdx["documentNamespace"]
    assert spdx["creationInfo"]["created"]
    assert any(
        creator.startswith("Tool:") for creator in spdx["creationInfo"]["creators"]
    )


def test_spdx_packages_list() -> None:
    spdx = _load(SPDX_PATH)
    packages = spdx["packages"]
    assert len(packages) > 0

    seen_ids = set()
    for package in packages:
        assert package["name"], package
        assert package["versionInfo"], package["name"]
        assert package["downloadLocation"], package["name"]
        assert package["licenseConcluded"], package["name"]
        assert package["licenseDeclared"], package["name"]
        spdx_id = package["SPDXID"]
        assert re.fullmatch(r"SPDXRef-[A-Za-z0-9.-]+", spdx_id), spdx_id
        assert spdx_id not in seen_ids, f"duplicate {spdx_id}"
        seen_ids.add(spdx_id)

    assert all(package["name"].lower() != "pedalboard" for package in packages), (
        "the build venv must not contain pedalboard; " + REGENERATE_HINT
    )


def test_spdx_relationships_resolve() -> None:
    spdx = _load(SPDX_PATH)
    package_ids = {package["SPDXID"] for package in spdx["packages"]} | {"SPDXRef-DOCUMENT"}

    describes = [
        rel for rel in spdx["relationships"] if rel["relationshipType"] == "DESCRIBES"
    ]
    assert describes, "the document must DESCRIBE the application package"
    assert describes[0]["relatedSpdxElement"] == "SPDXRef-Package-audio-studio"

    for relationship in spdx["relationships"]:
        assert relationship["spdxElementId"] in package_ids, relationship
        assert relationship["relatedSpdxElement"] in package_ids, relationship


def test_spdx_lgpl_selection_recorded_for_qt_binding() -> None:
    spdx = _load(SPDX_PATH)
    by_name = {package["name"]: package for package in spdx["packages"]}
    for name in ("pyside6-essentials", "shiboken6"):
        assert name in by_name, f"{name} missing from the venv SBOM"
        assert by_name[name]["licenseConcluded"] == "LGPL-3.0-only", (
            f"{name}: this project distributes Qt under LGPL-3.0; "
            "see THIRD_PARTY_LICENSES.md"
        )


# -- build report ---------------------------------------------------------------


def test_build_report_schema() -> None:
    report = _load(REPORT_PATH)

    assert report["schema_version"] == 1
    assert report["artifact"] == "linux-build-report"
    assert report["generated_by"] == "tools/generate_sbom.py"
    assert report["status"] in {"pass", "fail"}

    checks = report["checks"]
    expected_checks = {
        "bundle_present",
        "launcher_hashed",
        "qt_libraries_replaceable",
        "license_notices_shipped",
        "no_pedalboard_artifacts",
        "no_forbidden_distributions_bundled",
        "no_gpl_in_default_profile",
    }
    assert expected_checks <= set(checks)
    assert all(isinstance(value, bool) for value in checks.values())
    assert (report["status"] == "pass") is all(checks.values())

    outputs = report["sbom_outputs"]
    assert outputs["cyclonedx"] == ".agent_workspace/v1.1/linux-sbom.json"
    assert outputs["spdx"] == "packaging/SBOM.json"
    assert outputs["build_report"] == ".agent_workspace/v1.1/linux-build-report.json"


def test_build_report_bundle_evidence() -> None:
    report = _load(REPORT_PATH)
    bundle = report["bundle"]
    assert isinstance(bundle["present"], bool)

    if not bundle["present"]:
        assert report["status"] == "fail"
        return

    assert re.fullmatch(r"[0-9a-f]{64}", bundle["launcher_sha256"])
    assert bundle["total_bytes"] > 0
    assert bundle["file_count"] > 0
    assert bundle["qt_shared_libraries"], "LGPL replaceability requires visible Qt .so files"
    assert all(bundle["license_notices_present"].values())
    assert bundle["pedalboard_artifacts"] == []
    assert bundle["native_libraries"], "a desktop bundle without native libraries is wrong"

    sonames = {native["soname"].split(".so")[0] for native in bundle["native_libraries"]}
    assert any(name.startswith("libQt6Core") for name in sonames)
    assert any(name.startswith("libsndfile") for name in sonames)


def test_build_report_agrees_with_cyclonedx_on_bundled_distributions() -> None:
    report = _load(REPORT_PATH)
    sbom = _load(CYCLONEDX_PATH)

    report_names = {entry["name"] for entry in report["bundled_python_distributions"]}
    sbom_names = {
        component["name"]
        for component in sbom["components"]
        if component.get("purl") and _properties(component)["audio-studio:bundled"] == "true"
    }
    assert report_names == sbom_names
