function rc = run_all_verify(mode)
%RUN_ALL_VERIFY Master verification script for the MATLAB/Octave ports.
%
%   rc = run_all_verify()          'compare' mode (fast, the default):
%       golden compares only -- MATLAB port vs Python golden vectors on
%       identical exported inputs (heterodyne, qtec, homodyne core smoke)
%       plus compare_validate, which checks the COMMITTED per-validator
%       golden metric pairs (golden/validate_*_mat.mat vs *_py.mat).
%
%   rc = run_all_verify('full')    everything above, plus ALL statistical
%       validators re-run from scratch first (heterodyne H0-H6, qtec Q0-Q1,
%       homodyne validate_tracking / validate_off_mode / validate_zeta_sweep
%       / validate_residual_alignment / validate_app_30ms_100khz and the
%       ellipse validators).  The homodyne validators rewrite their
%       golden/validate_*_mat.mat metrics, so the final compare_validate
%       checks the FRESH outputs against the committed Python goldens.
%       Expect on the order of ten minutes of Octave runtime.
%
% The golden .mat files are committed under matlab/golden/; the missing
% heterodyne/qtec ones are regenerated by calling
%   python3 export_heterodyne_qtec_golden.py
% (requires python3 + numpy).
%
% Prints a summary table and returns rc = 0 iff everything passed.
  if nargin < 1
    mode = 'compare';
  end
  here = fileparts(mfilename('fullpath'));
  addpath(here);
  homodyne_setup_path();
  addpath(fullfile(here, 'heterodyne'));
  addpath(fullfile(here, 'qtec'));

  % -- golden data (regenerate on demand) ------------------------------------
  gdir = fullfile(here, 'golden');
  het_mat = fullfile(gdir, 'heterodyne_golden.mat');
  qtec_mat = fullfile(gdir, 'qtec_golden.mat');
  need = ~exist(het_mat, 'file') || ~exist(qtec_mat, 'file');
  ell_compare = exist(fullfile(here, 'homodyne', ...
                               'compare_ellipse_golden.m'), 'file') == 2;
  ell_mat = fullfile(gdir, 'ellipse_golden.mat');
  if ell_compare
    need = need || ~exist(ell_mat, 'file');
  end
  if need
    fprintf('golden data missing -- regenerating (python3 export)...\n');
    st = system(sprintf('python3 "%s"', ...
        fullfile(here, 'export_heterodyne_qtec_golden.py')));
    if st ~= 0
      error('run_all_verify: golden export failed (python3 + numpy needed)');
    end
    if ell_compare && ~exist(ell_mat, 'file')
      st = system(sprintf('python3 "%s"', ...
          fullfile(here, 'export_ellipse_golden.py')));
      if st ~= 0
        error('run_all_verify: ellipse golden export failed');
      end
    end
  end

  names = {};
  rcs = [];
  t0 = tic;

  % -- 'full' mode: re-run every statistical validator first ------------------
  % (the homodyne ones rewrite golden/validate_*_mat.mat, so compare_validate
  % below then verifies the fresh metrics against the committed Python side)
  if strcmp(mode, 'full')
    [names, rcs] = run_one(names, rcs, 'validate_heterodyne (H0-H6)', ...
                           @() validate_heterodyne());
    [names, rcs] = run_one(names, rcs, 'validate_diversity_p0_p1 (Q0-Q1)', ...
                           @() validate_diversity_p0_p1());
    [names, rcs] = run_one(names, rcs, 'validate_tracking (V1-V5)', ...
                           @() call0(@validate_tracking));
    [names, rcs] = run_one(names, rcs, 'validate_off_mode (O1-O6b)', ...
                           @() call0(@validate_off_mode));
    [names, rcs] = run_one(names, rcs, 'validate_zeta_sweep (Z0-Z3)', ...
                           @() call0(@validate_zeta_sweep));
    [names, rcs] = run_one(names, rcs, ...
                           'validate_residual_alignment (18 combos)', ...
                           @() call0(@validate_residual_alignment));
    [names, rcs] = run_one(names, rcs, 'validate_app_30ms_100khz (A1-A8)', ...
                           @() call0(@validate_app_30ms_100khz));
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_small_disp.m'), ...
             'file') == 2
      [names, rcs] = run_one(names, rcs, ...
                             'validate_ellipse_small_disp (E1-E5)', ...
                             @() validate_ellipse_small_disp());
    end
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_dynamic.m'), ...
             'file') == 2
      [names, rcs] = run_one(names, rcs, 'validate_ellipse_dynamic (D1-D2)', ...
                             @() validate_ellipse_dynamic());
    end
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_audit.m'), ...
             'file') == 2
      [names, rcs] = run_one(names, rcs, ...
                             'validate_ellipse_audit (review items 1-4)', ...
                             @() validate_ellipse_audit());
    end
  end

  % -- golden compares (both modes) -------------------------------------------
  [names, rcs] = run_one(names, rcs, 'compare_heterodyne_golden', ...
                         @() compare_heterodyne_golden(het_mat));
  [names, rcs] = run_one(names, rcs, 'compare_qtec_golden', ...
                         @() compare_qtec_golden(qtec_mat));
  if ell_compare
    [names, rcs] = run_one(names, rcs, 'compare_ellipse_golden', ...
                           @() compare_ellipse_golden(ell_mat));
  end

  % compare_with_python checks the committed MATLAB-side core smoke golden
  % against the committed Python-side golden.  Run export_golden_core
  % manually first to refresh the MATLAB side from the current code.
  if exist(fullfile(here, 'compare_with_python.m'), 'file') == 2 && ...
     exist(fullfile(gdir, 'core_smoke.mat'), 'file') == 2
    [names, rcs] = run_one(names, rcs, ...
                           'compare_with_python (homodyne core smoke)', ...
                           @() double(~compare_with_python()));
  end

  % compare_validate checks the per-validator golden metric pairs
  % (validate_*_mat.mat vs validate_*_py.mat) -- committed pairs in
  % 'compare' mode, freshly rewritten MATLAB side in 'full' mode.
  if exist(fullfile(here, 'compare_validate.m'), 'file') == 2
    [names, rcs] = run_one(names, rcs, ...
                           'compare_validate (validator golden pairs)', ...
                           @() call0(@compare_validate));
  end

  % -- summary -----------------------------------------------------------------
  fprintf('\n%s\n', repmat('=', 1, 72));
  fprintf('RUN_ALL_VERIFY SUMMARY (mode: %s)\n', mode);
  fprintf('%s\n', repmat('=', 1, 72));
  for i = 1:numel(names)
    if rcs(i) == 0
      tag = 'PASS';
    else
      tag = 'FAIL';
    end
    fprintf('  [%s] %s\n', tag, names{i});
  end
  if ~strcmp(mode, 'full')
    fprintf(['  (statistical validators not re-run; use ' ...
             'run_all_verify(''full'') to re-run\n   all of them ' ...
             '-- on the order of ten minutes)\n']);
  end
  rc = double(any(rcs ~= 0));
  if rc == 0
    fprintf('\nALL VERIFICATIONS PASSED  [elapsed %.1f s]\n', toc(t0));
  else
    fprintf('\nSOME VERIFICATIONS FAILED  [elapsed %.1f s]\n', toc(t0));
  end
end


function r = call0(f)
%CALL0 Run a zero-output verification function; success -> 0, errors raise.
  f();
  r = 0;
end


function [names, rcs] = run_one(names, rcs, label, fn)
%RUN_ONE Run one verification step; errors and nonzero returns count as FAIL.
  names{end + 1} = label;
  try
    r = fn();
    if isempty(r)
      r = 0;
    end
    rcs(end + 1) = double(any(r(:) ~= 0));
  catch err
    fprintf('  %s FAILED: %s\n', label, err.message);
    rcs(end + 1) = 1;
  end
end
