function rc = run_all_verify(mode)
%RUN_ALL_VERIFY Master verification script for the MATLAB/Octave ports.
%
%   rc = run_all_verify()        run every golden compare script (fast, the
%                                default): MATLAB port vs Python golden
%                                vectors on identical exported inputs.
%   rc = run_all_verify('full')  additionally run the full statistical
%                                validators (validate_heterodyne H0-H6,
%                                validate_diversity_p0_p1 Q0-Q1) -- several
%                                minutes of Octave runtime.
%
% The golden .mat files are committed under matlab/golden/; if missing they
% are regenerated by calling
%   python3 export_heterodyne_qtec_golden.py
% (requires python3 + numpy).
%
% Prints a summary table and returns rc = 0 iff everything passed.
  if nargin < 1
    mode = 'compare';
  end
  here = fileparts(mfilename('fullpath'));
  addpath(fullfile(here, 'homodyne'));          % set_rng, hd_* helpers
  addpath(fullfile(here, 'homodyne', 'core'));  % canonical shared core
  addpath(fullfile(here, 'heterodyne'));
  addpath(fullfile(here, 'qtec'));

  % -- golden data (regenerate on demand) ------------------------------------
  gdir = fullfile(here, 'golden');
  het_mat = fullfile(gdir, 'heterodyne_golden.mat');
  qtec_mat = fullfile(gdir, 'qtec_golden.mat');
  need = ~exist(het_mat, 'file') || ~exist(qtec_mat, 'file');
  ell_compare = exist(fullfile(here, 'homodyne', ...
                               'compare_ellipse_golden.m'), 'file') == 2;
  ell_mat = fullfile(gdir, 'ellipse_golden.mat');
  if ell_compare
    need = need || ~exist(ell_mat, 'file');
  end
  if need
    fprintf('golden data missing -- regenerating (python3 export)...\n');
    st = system(sprintf('python3 "%s"', ...
        fullfile(here, 'export_heterodyne_qtec_golden.py')));
    if st ~= 0
      error('run_all_verify: golden export failed (python3 + numpy needed)');
    end
    if ell_compare && ~exist(ell_mat, 'file')
      st = system(sprintf('python3 "%s"', ...
          fullfile(here, 'export_ellipse_golden.py')));
      if st ~= 0
        error('run_all_verify: ellipse golden export failed');
      end
    end
  end

  % -- run compare scripts ----------------------------------------------------
  names = {};
  rcs = [];
  t0 = tic;
  names{end + 1} = 'compare_heterodyne_golden';
  rcs(end + 1) = compare_heterodyne_golden(het_mat);
  names{end + 1} = 'compare_qtec_golden';
  rcs(end + 1) = compare_qtec_golden(qtec_mat);
  if ell_compare
    names{end + 1} = 'compare_ellipse_golden';
    rcs(end + 1) = compare_ellipse_golden(ell_mat);
  end

  % -- homodyne core smoke (committed goldens; errors on mismatch) ------------
  % compare_with_python checks the committed MATLAB-side golden against the
  % committed Python-side golden.  Run export_golden_core manually first to
  % refresh the MATLAB side from the current code.
  if exist(fullfile(here, 'compare_with_python.m'), 'file') == 2 && ...
     exist(fullfile(gdir, 'core_smoke.mat'), 'file') == 2
    names{end + 1} = 'compare_with_python (homodyne core smoke)';
    try
      ok = compare_with_python();
      rcs(end + 1) = double(~ok);
    catch err
      fprintf('  compare_with_python FAILED: %s\n', err.message);
      rcs(end + 1) = 1;
    end
  end

  % -- optionally the full statistical validators -----------------------------
  if strcmp(mode, 'full')
    names{end + 1} = 'validate_heterodyne (H0-H6)';
    rcs(end + 1) = validate_heterodyne();
    names{end + 1} = 'validate_diversity_p0_p1 (Q0-Q1)';
    rcs(end + 1) = validate_diversity_p0_p1();
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_small_disp.m'), ...
             'file') == 2
      names{end + 1} = 'validate_ellipse_small_disp (E1-E5)';
      rcs(end + 1) = validate_ellipse_small_disp();
    end
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_dynamic.m'), ...
             'file') == 2
      names{end + 1} = 'validate_ellipse_dynamic (D1-D2)';
      rcs(end + 1) = validate_ellipse_dynamic();
    end
    if exist(fullfile(here, 'homodyne', 'validate_ellipse_audit.m'), ...
             'file') == 2
      names{end + 1} = 'validate_ellipse_audit (review items 1-4)';
      rcs(end + 1) = validate_ellipse_audit();
    end
  end

  % -- summary -----------------------------------------------------------------
  fprintf('\n%s\n', repmat('=', 1, 72));
  fprintf('RUN_ALL_VERIFY SUMMARY\n');
  fprintf('%s\n', repmat('=', 1, 72));
  for i = 1:numel(names)
    if rcs(i) == 0
      tag = 'PASS';
    else
      tag = 'FAIL';
    end
    fprintf('  [%s] %s\n', tag, names{i});
  end
  if ~strcmp(mode, 'full')
    fprintf(['  (statistical validators not run; use run_all_verify(''full'')' ...
             ' to include\n   validate_heterodyne / validate_diversity_p0_p1' ...
             ' -- several minutes)\n']);
  end
  rc = double(any(rcs ~= 0));
  if rc == 0
    fprintf('\nALL VERIFICATIONS PASSED  [elapsed %.1f s]\n', toc(t0));
  else
    fprintf('\nSOME VERIFICATIONS FAILED  [elapsed %.1f s]\n', toc(t0));
  end
end
