"""Qt-free audio core: decoding, transport, buffering, editing and waveform summaries."""

from __future__ import annotations

from .edit_session import (
    AudioDocument,
    BaseSegment,
    Chunk,
    CutCommand,
    DeleteCommand,
    EditCommand,
    EditError,
    EditSession,
    FadeCommand,
    GainCommand,
    InsertSilenceCommand,
    PasteCommand,
    ReverseCommand,
    Segment,
    SilenceCommand,
    StreamingAudioDocument,
    StreamingEditSession,
    TrimCommand,
    UndoStack,
)
from .engine import AudioEngine
from .large_file import (
    DEFAULT_MEMORY_BUDGET_BYTES,
    MemoryBudgetError,
    check_memory_budget,
    is_large_container,
    should_stream,
)
from .loader import (
    SUPPORTED_EXTENSIONS,
    AudioLoadError,
    LoadedAudio,
    file_dialog_filter,
    load_audio,
    probe,
    probe_frames,
    resample,
    save_audio,
    supported_formats,
)
from .markers import Marker, MarkerItem, MarkerList, Region
from .output import AudioOutput, NullOutput, OutputDeviceError, PyAudioOutput, create_output
from .peaks import Envelope, PeakPyramid
from .recorder import RecordingTake, Take, TakeRegistry, TakeRegistryError
from .ring_buffer import RingBuffer
from .sample_source import (
    MemorySampleSource,
    SampleSource,
    StreamingSampleSource,
    open_source,
)
from .session import Bus, Clip, MasterBus, MultitrackSession, SessionMixer, Track
from .sounddevice_output import SoundDeviceOutput
from .sources import LoopSource, RegionSource
from .telemetry import EngineTelemetry, LevelSnapshot
from .types import (
    AudioBuffer,
    AudioFormat,
    LevelReading,
    TimeRange,
    TransportState,
    amplitude_to_db,
    db_to_amplitude,
    format_timecode,
)

__all__ = [
    "DEFAULT_MEMORY_BUDGET_BYTES",
    "SUPPORTED_EXTENSIONS",
    "AudioBuffer",
    "AudioDocument",
    "AudioEngine",
    "AudioFormat",
    "AudioLoadError",
    "AudioOutput",
    "BaseSegment",
    "Bus",
    "Chunk",
    "Clip",
    "CutCommand",
    "DeleteCommand",
    "EditCommand",
    "EditError",
    "EditSession",
    "EngineTelemetry",
    "Envelope",
    "FadeCommand",
    "GainCommand",
    "InsertSilenceCommand",
    "LevelReading",
    "LevelSnapshot",
    "LoadedAudio",
    "LoopSource",
    "Marker",
    "MarkerItem",
    "MarkerList",
    "MasterBus",
    "MemoryBudgetError",
    "MemorySampleSource",
    "MultitrackSession",
    "NullOutput",
    "OutputDeviceError",
    "PasteCommand",
    "PeakPyramid",
    "PyAudioOutput",
    "Region",
    "RegionSource",
    "RecordingTake",
    "ReverseCommand",
    "RingBuffer",
    "SampleSource",
    "Segment",
    "SessionMixer",
    "SilenceCommand",
    "SoundDeviceOutput",
    "StreamingSampleSource",
    "StreamingAudioDocument",
    "StreamingEditSession",
    "Take",
    "TakeRegistry",
    "TakeRegistryError",
    "TimeRange",
    "Track",
    "TransportState",
    "TrimCommand",
    "UndoStack",
    "amplitude_to_db",
    "check_memory_budget",
    "create_output",
    "db_to_amplitude",
    "file_dialog_filter",
    "format_timecode",
    "is_large_container",
    "load_audio",
    "open_source",
    "probe",
    "probe_frames",
    "resample",
    "save_audio",
    "should_stream",
    "supported_formats",
]
